[project]
name = "pjbot"
version = "0.1.0"
description = "Bot for encrypt"
readme = "README.md"
requires-python = ">=3.12"
env-file = ".env"
dependencies = [
    "aiogram>=3.22.0",
    "aiosqlite>=0.21.0",
    "cryptography>=46.0.2",
    "python-dotenv>=1.1.1",
]

